package com.mis2016bd.tpfmz.modelo;
// Generated 24/03/2017 19:53:27 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje{


     private Short id;
     private Usuario usuarioByUsuarioDestinatario;
     private Usuario usuarioByUsuarioRemitente;
     private Date fecha;
     private String contenido;

    public Mensaje() {
    }

    public Mensaje(Usuario usuarioByUsuarioDestinatario, Usuario usuarioByUsuarioRemitente, Date fecha, String contenido) {
       this.usuarioByUsuarioDestinatario = usuarioByUsuarioDestinatario;
       this.usuarioByUsuarioRemitente = usuarioByUsuarioRemitente;
       this.fecha = fecha;
       this.contenido = contenido;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public Usuario getUsuarioByUsuarioDestinatario() {
        return this.usuarioByUsuarioDestinatario;
    }
    
    public void setUsuarioByUsuarioDestinatario(Usuario usuarioByUsuarioDestinatario) {
        this.usuarioByUsuarioDestinatario = usuarioByUsuarioDestinatario;
    }
    public Usuario getUsuarioByUsuarioRemitente() {
        return this.usuarioByUsuarioRemitente;
    }
    
    public void setUsuarioByUsuarioRemitente(Usuario usuarioByUsuarioRemitente) {
        this.usuarioByUsuarioRemitente = usuarioByUsuarioRemitente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }




}


